name: Build and Notify Discord

on:
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Notify Discord: Build Started
      - name: Notify Discord: Build Started
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: >
            {
              "username": "SporeAPI Build",
              "embeds": [
                {
                  "title": "⚡ Build Started: ${{ github.event.release.tag_name }}",
                  "description": "Building the release...",
                  "url": "${{ github.event.release.html_url }}",
                  "color": 16763904
                }
              ]
            }

      # 2️⃣ Run the Gradle build
      - name: Run Gradle Build
        run: ./gradlew build
        continue-on-error: true
        id: gradle_build

      # 3️⃣ Notify Discord: Build Success
      - name: Notify Discord: Build Success
        if: success() && steps.gradle_build.outcome == 'success'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: >
            {
              "username": "SporeAPI Build",
              "embeds": [
                {
                  "title": "✅ Build Succeeded: ${{ github.event.release.tag_name }}",
                  "description": "Release build completed successfully.",
                  "url": "${{ github.event.release.html_url }}",
                  "color": 3066993
                }
              ]
            }

      # 4️⃣ Notify Discord: Build Failed
      - name: Notify Discord: Build Failed
        if: failure() || steps.gradle_build.outcome != 'success'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: >
            {
              "username": "SporeAPI Build",
              "embeds": [
                {
                  "title": "❌ Build Failed: ${{ github.event.release.tag_name }}",
                  "description": "Check the build logs: [View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
                  "url": "${{ github.event.release.html_url }}",
                  "color": 15158332
                }
              ]
            }
